### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by bconsolvo** [oneapi-src/credit-card-fraud-detection#3]
When I go to run 
```python ./src/run_benchmarks_train.py -l ./logs/stock_training.log```,
I get this numpy ValueError:
```
Traceback (most recent call last):
  File "/home/u151382/Consolvo/20221027_creditcardfraud/credit-card-fraud-detection/./src/run_benchmarks_train.py", line 15, in <module>
    from utils.training import split_data, DBSCAN_Clustering, lgbm_model_train
  File "/home/u151382/Consolvo/20221027_creditcardfraud/credit-card-fraud-detection/src/utils/training.py", line 11, in <module>
    from lightgbm import LGBMClassifier
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/lightgbm/basic.py", line 20, in <module>
    from .compat import PANDAS_INSTALLED, concat, dt_DataTable, is_dtype_sparse, pd_DataFrame, pd_Series
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/lightgbm/compat.py", line 6, in <module>
    from pandas import DataFrame as pd_DataFrame
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/u151382/.conda/envs/FraudDetection_stock/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by bconsolvo** [comment]
I decided to upgrade numpy, and got further incompatibilities by installing the newest numpy.

```
pip install --upgrade numpy
Requirement already satisfied: numpy in /home/u151382/.local/lib/python3.9/site-packages (1.19.5)
Collecting numpy
  Downloading numpy-1.23.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     |████████████████████████████████| 17.1 MB 4.3 MB/s 
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.16.2 requires pyyaml>=5.1, which is not installed.
transformers 4.16.2 requires requests, which is not installed.
transformers 4.16.2 requires tqdm>=4.27, which is not installed.
openvino-dev 2022.1.0 requires defusedxml>=0.7.1, which is not installed.
openvino-dev 2022.1.0 requires pyyaml>=5.4.1, which is not installed.
openvino-dev 2022.1.0 requires requests>=2.25.1, which is not installed.
openvino-dev 2022.1.0 requires tqdm>=4.54.1, which is not installed.
openvino 2022.1.0 requires numpy<1.20,>=1.16.6, but you have numpy 1.23.4 which is incompatible.
openvino-dev 2022.1.0 requires numpy<1.20,>=1.16.6, but you have numpy 1.23.4 which is incompatible.
openvino-dev 2022.1.0 requires numpy<=1.21,>=1.16.6; python_version > "3.6", but you have numpy 1.23.4 which is incompatible.
openvino-dev 2022.1.0 requires pandas~=1.1.5, but you have pandas 1.5.1 which is incompatible.
openvino-dev 2022.1.0 requires scikit-learn~=0.24.1, but you have scikit-learn 1.1.3 which is incompatible.
openvino-dev 2022.1.0 requires scipy~=1.5.4, but you have scipy 1.9.3 which is incompatible.
Successfully installed numpy-1.23.4
```
